import { ArrowRight, Check, Cylinder, MapPin, Minus, Plus } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'wouter';

export default function Booking() {
  const [quantity, setQuantity] = useState(1);
  const [booked, setBooked] = useState(false);
  return <div className="standard-page booking-page"><div className="page-intro"><div><span className="section-kicker">New refill request</span><h2>Book your next <em>cylinder.</em></h2><p>Choose your refill and we’ll keep the handoff visible from here.</p></div><span className="demo-pill"><span className="live-dot" /> Demo mode</span></div><div className="booking-form-layout"><section className="form-card"><div className="form-section"><span className="eyebrow">1 / Cylinder type</span><div className="product-option is-selected"><span className="cylinder-illustration small"><Cylinder size={27} /></span><div><strong>Domestic LPG cylinder</strong><small>14.2 kg · Standard refill</small></div><Check size={18} /></div></div><div className="form-section"><span className="eyebrow">2 / Quantity</span><div className="quantity-control"><button onClick={() => setQuantity(Math.max(1, quantity - 1))} aria-label="Decrease quantity"><Minus size={16} /></button><strong>{String(quantity).padStart(2, '0')}</strong><button onClick={() => setQuantity(quantity + 1)} aria-label="Increase quantity"><Plus size={16} /></button></div></div><div className="form-section"><span className="eyebrow">3 / Delivery address</span><div className="address-option"><MapPin size={18} /><div><strong>18, 4th Cross, Indiranagar</strong><small>Bengaluru, Karnataka 560038</small></div><button className="text-button">Edit</button></div></div><div className="form-summary"><span><strong>{quantity} ×</strong> 14.2 kg cylinder</span><span className="summary-total">₹ 903</span></div><button className="button button-primary button-wide" onClick={() => setBooked(true)}>{booked ? 'Booking request received' : 'Confirm refill request'} <ArrowRight size={16} /></button>{booked && <div className="success-callout"><Check size={17} /><div><strong>Your request is in the queue</strong><span>We’ll assign a delivery partner and start live tracking when it moves.</span></div></div>}</section><aside className="booking-aside"><div className="aside-art"><div className="art-glow" /><Cylinder size={70} strokeWidth={1.1} /></div><span className="eyebrow">What happens next</span><ul className="next-list"><li><span>01</span><div><strong>We confirm your request</strong><small>A booking ID appears in your history.</small></div></li><li><span>02</span><div><strong>A delivery partner is assigned</strong><small>You’ll see who is carrying the cylinder.</small></div></li><li><span>03</span><div><strong>You can track the route</strong><small>ETA updates as the vehicle moves.</small></div></li></ul><Link href="/customer/track" className="text-link text-link-dark">View current demo route <ArrowRight size={14} /></Link></aside></div></div>;
}
