// Warm Terracotta customer profile: editable cream form, cherry typography, and orange save confirmation.
import { Bell, Check, ChevronRight, LockKeyhole, MapPin, Pencil, Phone, Save, ShieldCheck, UserRound, Mail, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useAuth } from '../../contexts/AuthContext';

export default function Profile() {
  const { profile, updateProfile } = useAuth();
  const [editing, setEditing] = useState(false);
  const [saved, setSaved] = useState(false);
  const [form, setForm] = useState(profile);
  useEffect(() => setForm(profile), [profile]);
  function change(key, value) { setForm((current) => ({ ...current, [key]: value })); }
  function save(event) { event.preventDefault(); updateProfile('customer', form); setEditing(false); setSaved(true); window.setTimeout(() => setSaved(false), 2600); }
  return <div className="standard-page profile-page"><div className="page-intro"><div><span className="section-kicker">Your SmartTrack account</span><h2>{profile.name.split(' ')[0]} <em>{profile.name.split(' ').slice(1).join(' ')}.</em></h2><p>Manage your delivery details and notification preferences.</p></div><div className="profile-avatar-large">{profile.name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase()}</div></div>{saved && <div className="save-confirmation"><Check size={16} /> Profile changes saved for this demo session.</div>}<div className="profile-layout"><section className="profile-card"><div className="profile-card-heading"><span className="eyebrow">Personal details</span>{editing ? <button className="text-button" type="button" onClick={() => { setForm(profile); setEditing(false); }}><X size={14} /> Cancel</button> : <button className="text-button" type="button" onClick={() => setEditing(true)}><Pencil size={14} /> Edit profile</button>}</div>{editing ? <form className="profile-edit-form" onSubmit={save}><label>Full name<input value={form.name} onChange={(event) => change('name', event.target.value)} required /></label><label>Phone number<input value={form.phone} onChange={(event) => change('phone', event.target.value)} required /></label><label>Email<input type="email" value={form.email} onChange={(event) => change('email', event.target.value)} required /></label><label>Default delivery address<textarea value={form.address} onChange={(event) => change('address', event.target.value)} rows={3} required /></label><button className="button button-orange" type="submit"><Save size={15} /> Save changes</button></form> : <><div className="profile-field"><UserRound size={17} /><span><small>Name</small><strong>{profile.name}</strong></span></div><div className="profile-field"><Phone size={17} /><span><small>Phone</small><strong>{profile.phone}</strong></span></div><div className="profile-field"><Mail size={17} /><span><small>Email</small><strong>{profile.email}</strong></span></div><div className="profile-field"><MapPin size={17} /><span><small>Default delivery address</small><strong>{profile.address}</strong></span></div></>}</section><section className="profile-card"><span className="eyebrow">Preferences</span>{[['Delivery notifications', 'Get updates as your delivery moves.', Bell], ['Secure verification', 'OTP required for every handoff.', ShieldCheck], ['Privacy & security', 'Your data stays connected to your account.', LockKeyhole]].map(([title, copy, Icon]) => <button className="preference-row" key={title} type="button"><span className="preference-icon"><Icon size={16} /></span><span><strong>{title}</strong><small>{copy}</small></span><ChevronRight size={16} /></button>)}</section></div></div>;
}
