import { ArrowRight, Check, Clock3, Map, MapPin, Radio, ShieldCheck, Sparkles, Truck, Waypoints, Zap } from 'lucide-react';
import { Link } from 'wouter';
import BrandLogo from '../components/brand/BrandLogo';
import { routePoints } from '../services/mockData';

const heroArt = '/manus-storage/lpg-smarttrack-reference_47ca9d9a.png';

export default function Landing() {
  return <div className="landing-page">
    <header className="landing-nav"><Link href="/"><BrandLogo light /></Link><nav><a href="#how-it-works">How it works</a><a href="#why">Why SmartTrack</a><a href="#future">Future scope</a></nav><div className="landing-actions"><Link href="/login?role=customer" className="text-link">Customer login <ArrowRight size={15} /></Link><Link href="/login?role=agent" className="button button-light button-small">Agent login</Link></div></header>
    <main>
      <section className="hero-section"><div className="hero-visual" style={{ backgroundImage: 'url(' + heroArt + ')' }}><div className="hero-visual-fade" /><div className="hero-map-label label-one"><span className="live-dot" /> DELIVERY NETWORK <strong>LIVE</strong></div><div className="hero-map-label label-two"><MapPin size={14} /> Home address</div><div className="hero-route-note"><span className="route-note-line" /><div><span className="eyebrow">Current route</span><strong>Warehouse → Indiranagar</strong></div></div></div><div className="hero-copy"><span className="section-kicker"><span className="live-dot" /> Live delivery intelligence</span><h1>Know exactly when your LPG delivery will arrive.</h1><p>Real-time delivery tracking, intelligent ETA, and secure customer verification — all in one calm, connected platform.</p><div className="hero-ctas"><Link href="/login?role=customer&next=%2Fcustomer%2Ftrack" className="button button-primary">Track my delivery <ArrowRight size={17} /></Link><Link href="/login?role=agent&next=%2Fagent%2Fdashboard" className="button button-ghost">Agent login <ArrowRight size={17} /></Link></div><div className="hero-proof"><span><Check size={15} /> No account required for demo</span><span><Check size={15} /> OTP-secured handoff</span></div></div></section>
      <section className="signal-strip"><div><Radio size={17} /><span>DEMO MODE <strong>ACTIVE</strong></span></div><div><span className="strip-line" /><span>One shared view from booking to doorstep</span></div><div><span>Built for the last mile</span><ArrowRight size={16} /></div></section>
      <section className="section-shell how-section" id="how-it-works"><div className="section-intro"><span className="section-kicker">01 / How it works</span><h2>One clear handoff,<br /><em>every step visible.</em></h2><p>SmartTrack turns the uncertain minutes between “booked” and “delivered” into a simple, trackable journey.</p></div><div className="flow-steps">{[['01','Book LPG','Start with a simple refill request.',MapPin],['02','Delivery assigned','Know who is carrying it.',Truck],['03','Track vehicle','Watch the route move live.',Map],['04','Get ETA alert','Plan around the doorstep.',Clock3],['05','Verify delivery','Confirm with a secure OTP.',ShieldCheck]].map(([num,title,copy,Icon], index) => <div className="flow-step" key={num}><span className="flow-number">{num}</span><div className="flow-icon"><Icon size={19} /></div><h3>{title}</h3><p>{copy}</p>{index < 4 && <span className="flow-arrow"><ArrowRight size={16} /></span>}</div>)}</div></section>
      <section className="section-shell feature-showcase"><div className="showcase-copy"><span className="section-kicker">02 / Live GPS tracking</span><h2>Your delivery,<br /><em>in motion.</em></h2><p>See the vehicle, the route, and the last updated location in one glance. No refreshing. No guessing.</p><div className="feature-points"><div><span className="point-icon"><Map size={16} /></span><span><strong>Live route line</strong><small>Follow the same map your delivery partner sees.</small></span></div><div><span className="point-icon"><Zap size={16} /></span><span><strong>Smart ETA</strong><small>Distance and travel time recalculate as the route moves.</small></span></div><div><span className="point-icon"><Radio size={16} /></span><span><strong>Proximity alerts</strong><small>Get a calm nudge when your cylinder is almost home.</small></span></div></div><Link href="/login?role=customer&next=%2Fcustomer%2Ftrack" className="text-link text-link-dark">Open live tracking <ArrowRight size={15} /></Link></div><div className="showcase-map"><div className="showcase-map-art" role="img" aria-label="Signal Cyan route moving from a delivery vehicle to a customer"><span className="mini-map-label"><span className="live-dot" /> LIVE ROUTE / 06 WAYPOINTS</span><svg viewBox="0 0 700 450" aria-hidden="true"><path d="M70 365 C140 330, 146 270, 218 286 S300 350, 358 290 S420 170, 490 212 S585 245, 660 100" fill="none" stroke="#37d4e5" strokeWidth="7" strokeLinecap="round" strokeDasharray="2 18" /><path d="M70 365 C140 330, 146 270, 218 286 S300 350, 358 290 S420 170, 490 212 S585 245, 660 100" fill="none" stroke="#37d4e5" strokeOpacity=".2" strokeWidth="18" strokeLinecap="round" /></svg><span className="mini-vehicle"><Truck size={17} /></span><span className="mini-home"><MapPin size={19} /></span><span className="mini-waypoint waypoint-a" /><span className="mini-waypoint waypoint-b" /><span className="mini-waypoint waypoint-c" /></div><div className="showcase-map-card"><span className="live-dot" /><div><span className="eyebrow">Delivery arriving</span><strong>14 min</strong></div><span>5.2 km</span></div></div></section>
      <section className="section-shell split-feature"><div className="split-visual"><div className="split-visual-art" role="img" aria-label="Secure route handoff instrument"><div className="signal-phone-header"><span>DELIVERY SIGNAL</span><b>LIVE</b></div><div className="signal-phone-route"><svg viewBox="0 0 280 310" aria-hidden="true"><path d="M30 34 C178 72, 68 128, 186 162 S234 254, 152 285" fill="none" stroke="#37d4e5" strokeWidth="5" strokeDasharray="2 13" strokeLinecap="round" /><path d="M30 34 C178 72, 68 128, 186 162 S234 254, 152 285" fill="none" stroke="#37d4e5" strokeOpacity=".18" strokeWidth="15" strokeLinecap="round" /></svg><span className="signal-stop stop-start" /><span className="signal-stop stop-mid" /><span className="signal-stop stop-end" /></div><div className="signal-phone-bottom"><span className="eyebrow">Current route</span><strong>Approaching Indiranagar</strong><small>OTP verification follows arrival</small></div></div><div className="otp-card"><div className="otp-card-mark"><ShieldCheck size={18} /></div><div><span className="eyebrow">Doorstep handoff</span><strong>Secure by default</strong><small>6-digit OTP verification</small></div><Check size={18} className="otp-check" /></div></div><div className="split-copy"><span className="section-kicker">03 / Trust at the doorstep</span><h2>Visibility builds<br /><em>confidence.</em></h2><p>The final moment matters. SmartTrack closes the loop with a simple OTP confirmation, so both sides know the handoff is complete.</p><div className="trust-line"><span><ShieldCheck size={17} /> Customer verification</span><span><Waypoints size={17} /> Digital delivery history</span></div><Link href="/login?role=customer&next=%2Fcustomer%2Fverify" className="button button-dark">See verification flow <ArrowRight size={16} /></Link></div></section>
      <section className="section-shell why-section" id="why"><div className="section-intro intro-wide"><span className="section-kicker">04 / Why SmartTrack</span><h2>Less waiting.<br /><em>More certainty.</em></h2></div><div className="advantage-grid">{[['01','Real-time visibility','Know whether your cylinder is booked, assigned, moving, or nearly home.'],['02','Accurate ETA','Make the last mile measurable with distance-aware, evolving arrival time.'],['03','Transparent delivery','One shared state for customers and delivery partners—no black box.'],['04','Better communication','Proximity alerts arrive when they are useful, not when they are noise.'],['05','Secure handoff','A simple OTP keeps the final confirmation clear and accountable.'],['06','Digital history','Every delivery becomes an accessible, verified record.']].map(([num,title,copy]) => <article className="advantage-card" key={num}><span className="advantage-number">{num}</span><div><h3>{title}</h3><p>{copy}</p></div><ArrowRight size={17} /></article>)}</div></section>
      <section className="future-section" id="future"><div className="future-inner"><div><span className="section-kicker">05 / Future scope</span><h2>Ready for the<br /><em>real last mile.</em></h2><p>Today’s demo runs on realistic mock data. Tomorrow, the same interfaces can plug into live GPS, OSRM routing, Socket.IO events, PostgreSQL/PostGIS, Redis, and FCM notifications.</p><Link href="/login?role=agent&next=%2Fagent%2Factive" className="button button-cyan">Open agent demo <ArrowRight size={16} /></Link></div><div className="future-stack"><div><span>01</span><strong>Live GPS</strong><small>Browser geolocation + delivery telemetry</small></div><div><span>02</span><strong>Route intelligence</strong><small>OSRM geometry + traffic-aware ETA</small></div><div><span>03</span><strong>Verified delivery</strong><small>Secure customer handoff + history</small></div></div></div></section>
    </main>
    <footer className="landing-footer"><div><BrandLogo light /><p>From booking to doorstep — live.</p></div><div className="footer-note"><span className="live-dot" /> Independent college / hackathon prototype</div><Link href="/login?role=admin" className="landing-admin-link"><ShieldCheck size={13} /> Admin ops</Link><span>© 2026 LPG SmartTrack</span></footer>
  </div>;
}
