import { ArrowLeft, Check, MapPin, Navigation, Phone, ShieldCheck, Truck, UserRound } from 'lucide-react';
import { Link } from 'wouter';
import LiveMap from '../../components/map/LiveMap';
import ETACard from '../../components/delivery/ETACard';
import GPSDemoControls from '../../components/delivery/GPSDemoControls';
import StatusBadge from '../../components/common/StatusBadge';
import { useDelivery } from '../../contexts/DeliveryContext';

export default function ActiveDelivery() { const { delivery, routePoints, customer, start, pause, reset, markArrived, complete } = useDelivery(); const arrived = delivery.status === 'arrived'; const delivered = delivery.status === 'delivered'; return <div className="active-delivery-page"><div className="active-heading"><div><Link href="/agent/deliveries" className="back-link"><ArrowLeft size={15} /> Today’s deliveries</Link><h2>Active <em>delivery.</em></h2></div><StatusBadge tone={delivered ? 'success' : arrived ? 'warning' : 'orange'} live>{delivered ? 'Delivered' : arrived ? 'Arrived' : 'Out for delivery'}</StatusBadge></div><div className="active-layout"><section className="active-map-card"><LiveMap delivery={delivery} routePoints={routePoints} customer={customer} /><GPSDemoControls delivery={delivery} onStart={start} onPause={pause} onReset={reset} /></section><aside className="active-side"><ETACard delivery={delivery} dark /><div className="customer-detail-card"><div className="card-heading"><div><span className="eyebrow">Next handoff</span><h3>Customer details</h3></div><span className="customer-avatar">AR</span></div><div className="customer-line"><UserRound size={16} /><span><small>Name</small><strong>Ananya Rao</strong></span></div><div className="customer-line"><MapPin size={16} /><span><small>Address</small><strong>18, 4th Cross, Indiranagar</strong></span></div><div className="customer-line"><Phone size={16} /><span><small>Phone</small><strong>+91 98765 43210</strong></span></div><div className="customer-line"><Navigation size={16} /><span><small>Booking ID</small><strong>{delivery.id}</strong></span></div></div><div className="agent-actions">{!arrived && !delivered && <button className="button button-primary button-wide" onClick={markArrived}><MapPin size={16} /> Mark arrived</button>}{arrived && !delivered && <Link href="/customer/verify" className="button button-cyan button-wide"><ShieldCheck size={16} /> Open OTP verification</Link>}{arrived && !delivered && <button className="button button-dark button-wide" onClick={complete}><Check size={16} /> Complete delivery</button>}{delivered && <div className="success-callout"><Check size={17} /><div><strong>Handoff verified</strong><span>This delivery is complete and visible in history.</span></div></div>}</div></aside></div><div className="active-flow"><span className="eyebrow">Agent flow</span><div><span className="flow-state is-done"><Truck size={15} /> Start delivery</span><i /> <span className={'flow-state ' + (delivery.status !== 'assigned' ? 'is-done' : '')}><Navigation size={15} /> Out for delivery</span><i /><span className={'flow-state ' + (arrived || delivered ? 'is-done' : '')}><MapPin size={15} /> Arrived</span><i /><span className={'flow-state ' + (delivered ? 'is-done' : '')}><ShieldCheck size={15} /> Verified</span></div></div></div>; }
