// Warm Terracotta delivery monitor: route risk is visible, and intervention actions stay explicit and reversible in demo mode.
import { AlertTriangle, ArrowRight, CheckCircle2, Filter, MapPin, Radio, ShieldAlert, Truck } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useDelivery } from '../../contexts/DeliveryContext';
import { adminDeliveries as initialDeliveries } from '../../services/adminData';

export default function AdminDeliveries() {
  const [items, setItems] = useState(initialDeliveries);
  const [filter, setFilter] = useState('All');
  const { sendPush, pause } = useDelivery();
  const filters = ['All', 'Live', 'Flagged', 'Delivered'];
  const visible = useMemo(() => items.filter((item) => filter === 'All' || filter === 'Live' && item.status === 'Out for delivery' || filter === 'Flagged' && item.status === 'Flagged' || filter === 'Delivered' && item.status === 'Delivered'), [items, filter]);
  function flagDelivery(id) { setItems((current) => current.map((item) => item.id === id ? { ...item, status: item.status === 'Flagged' ? 'Assigned' : 'Flagged', risk: item.status === 'Flagged' ? 'Medium' : 'High' } : item)); const item = items.find((delivery) => delivery.id === id); sendPush('Delivery review signal', `${item?.id || 'Delivery'} was flagged for a security review.`, 'Admin operators'); }
  return <div className="admin-page"><div className="page-intro"><div><span className="section-kicker">Movement monitor / Admin only</span><h2>Delivery <em>control room.</em></h2><p>See every active handoff, spot route risk, and keep operational actions accountable.</p></div><span className="admin-live-pill"><Radio size={13} /> GPS stream connected</span></div><div className="admin-toolbar"><div className="admin-filter-tabs">{filters.map((item) => <button type="button" className={filter === item ? 'is-active' : ''} onClick={() => setFilter(item)} key={item}>{item}{item === 'All' && <span>{items.length}</span>}</button>)}</div><span className="toolbar-note"><Filter size={14} /> {visible.length} visible deliveries</span></div><section className="admin-table-card admin-deliveries-table"><div className="admin-table-head"><span>Delivery</span><span>Customer / agent</span><span>Zone</span><span>Status</span><span>Risk</span><span>Action</span></div>{visible.map((item) => <div className={'admin-table-row ' + (item.status === 'Flagged' ? 'is-risk-row' : '')} key={item.id}><div className="admin-delivery-cell"><span className={'delivery-status-icon ' + (item.status === 'Flagged' ? 'is-flagged' : '')}>{item.status === 'Delivered' ? <CheckCircle2 size={16} /> : item.status === 'Flagged' ? <AlertTriangle size={16} /> : <Truck size={16} />}</span><span><strong>{item.id}</strong><small>{item.updated}</small></span></div><span className="admin-route-pair"><strong>{item.customer}</strong><small>with {item.agent}</small></span><span className="admin-zone"><MapPin size={13} /> {item.zone}</span><span className={'delivery-status-label ' + item.status.toLowerCase().replaceAll(' ', '-')}>{item.status}<small>{item.eta}</small></span><span className={'risk-label risk-' + item.risk.toLowerCase()}><i /> {item.risk}</span><div className="admin-row-actions"><button className="icon-action icon-action-warm" type="button" title={item.status === 'Flagged' ? 'Clear review flag' : 'Flag for review'} onClick={() => flagDelivery(item.id)}><ShieldAlert size={15} /></button>{item.status === 'Out for delivery' && <button className="icon-action" type="button" title="Hold live GPS stream" onClick={pause}><Radio size={15} /></button>}<button className="icon-action" type="button" title="Open delivery detail"><ArrowRight size={15} /></button></div></div>)}{visible.length === 0 && <div className="admin-empty"><Truck size={18} /><strong>No deliveries in this filter</strong><span>Change the status filter to inspect another queue.</span></div>}</section></div>;
}
