// Warm Terracotta user monitor: verification, presence, and restrained account actions for security operations.
import { CheckCircle2, MailCheck, Search, ShieldAlert, UserRound, UserX } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useDelivery } from '../../contexts/DeliveryContext';
import { adminUsers as initialUsers } from '../../services/adminData';

export default function AdminUsers() {
  const [users, setUsers] = useState(initialUsers);
  const [query, setQuery] = useState('');
  const { sendPush } = useDelivery();
  const visible = useMemo(() => users.filter((user) => `${user.name} ${user.email} ${user.id} ${user.role}`.toLowerCase().includes(query.toLowerCase())), [users, query]);
  function toggleLock(id) { setUsers((current) => current.map((user) => user.id === id ? { ...user, status: user.status === 'Suspended' ? 'Active' : 'Suspended' } : user)); const user = users.find((item) => item.id === id); sendPush(user?.status === 'Suspended' ? 'Account restored' : 'Account access paused', `${user?.name || 'A user'} security access was updated by an admin.`, 'Security audit'); }
  function sendVerification(user) { sendPush('Email verification reminder', `A verification reminder is ready for ${user.name}.`, user.email); setUsers((current) => current.map((item) => item.id === user.id ? { ...item, verification: 'Reminder sent' } : item)); }
  return <div className="admin-page"><div className="page-intro"><div><span className="section-kicker">Identity monitor / Admin only</span><h2>Users <em>and access.</em></h2><p>Review presence, role, and verification state before taking a controlled action.</p></div><span className="admin-live-pill"><UserRound size={13} /> {users.length} records</span></div><div className="admin-toolbar"><div className="admin-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email, or user ID" /></div><span className="toolbar-note"><ShieldAlert size={14} /> Actions are recorded in the demo audit stream</span></div><section className="admin-table-card admin-users-table"><div className="admin-table-head"><span>User</span><span>Role</span><span>Presence</span><span>Email verification</span><span>Last seen</span><span>Action</span></div>{visible.map((user) => <div className="admin-table-row" key={user.id}><div className="admin-user-cell"><span className="admin-user-avatar">{user.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</span><span><strong>{user.name}</strong><small>{user.id} · {user.email}</small></span></div><span className="admin-role-chip">{user.role}</span><span className={'presence-label ' + (user.status === 'Offline' ? 'is-offline' : user.status === 'Suspended' ? 'is-suspended' : '')}><i /> {user.status}</span><span className={'verification-label ' + (user.verification === 'Email verified' ? 'is-verified' : '')}>{user.verification === 'Email verified' ? <CheckCircle2 size={14} /> : <MailCheck size={14} />} {user.verification}</span><span className="muted-note">{user.lastSeen}</span><div className="admin-row-actions">{user.verification !== 'Email verified' && <button className="icon-action icon-action-warm" type="button" onClick={() => sendVerification(user)} title="Send email verification reminder"><MailCheck size={15} /></button>}<button className="icon-action" type="button" onClick={() => toggleLock(user.id)} title={user.status === 'Suspended' ? 'Restore access' : 'Pause access'}>{user.status === 'Suspended' ? <CheckCircle2 size={15} /> : <UserX size={15} />}</button></div></div>)}{visible.length === 0 && <div className="admin-empty"><Search size={18} /><strong>No matching users</strong><span>Try a name, role, email, or user ID.</span></div>}</section></div>;
}
